#!/bin/bash
#
# Autor: Thyago Ismael
#
# shounenjump: Pequeno programa para baixar a Revista Shounen Jump
#
# Atenção!
# 1. A revista está em JAPONÊS.
# 2. É criada uma pasta com imagens das páginas no formato jpeg
#    no local onde o programa é chamado.


escolherVolume() {
  URL_BASE='https://rawmanga.top/Weekly-Shonen-Jump'

  curl -s $URL_BASE | grep '^<a href.*Shonen' |
    sed 's/[^"]*"// ; s/".*//' | # remove a sintaxe do html
    cut --delimiter '/' --fields 5 | # usa campo do volume
    fzf --prompt='Qual o volume? '

}

baixar(){
  # $1 é o volume da revista

  URL_BASE="https://rawmanga.top/viewer/Weekly-Shonen-Jump/$1"

  test -d $1 || mkdir $1 2> /dev/null
  cd $1

  NUM_PAGINA=1
  while wget -O "$(tresDigitos $NUM_PAGINA).jpeg" --quiet --continue "$URL_BASE/$NUM_PAGINA"
  do
    echo -en "Páginas: $NUM_PAGINA\r"

    NUM_PAGINA=$(( NUM_PAGINA+1 ))
  done

  echo 'Completo!'
}

tresDigitos(){
  n=$1
  test $1 -lt 100 && eval n="0$1"
  test $1 -lt 10  && eval n="0$1"

  echo $n
}

baixar $(escolherVolume)
