#!/bin/bash
#
# Autor: Thyago Ismael
#
# zasshi : Tiny script to downloads raw mangas
#


MAIN_DIRECTORY="$HOME/Zasshi"
LINKS_FILE="$MAIN_DIRECTORY/following.txt"

create_directories(){
  test -d "$MAIN_DIRECTORY" || mkdir -p "$MAIN_DIRECTORY"

  if test ! -f "$LINKS_FILE"
  then
    touch "$LINKS_FILE"
    echo "# Here you can put links to your favorites" >> "$LINKS_FILE"
    echo "# magazines or mangas (only from rawmanga.top)" >> "$LINKS_FILE"
  fi
}

chooseManga(){
  # Blank lines or with a leading # are ignored
  sed "/^#/ d; /^ *$/ d" $LINKS_FILE | fzf --prompt='Which magazine? '
}

chooseChapter() {
  LINK=$1

  CHAPTER=$(curl -s $LINK | grep "$LINK" | grep -v "class" |
    sed 's/[^"]*"// ; s/".*//' | # remove html syntax
    cut --delimiter '/' --fields 5 | # uses volume field
    fzf --prompt='Which volume? ')

  test "$CHAPTER" || exit
  echo "$LINK/$CHAPTER"
}

downloadChapter(){
  # $1 is the chapter URL 

  NAME=$(cutField $1 4)
  CHAPTER=$(cutField $1 5)
  echo "$NAME $CHAPTER"

  test "$1" || exit
  test -d "$MAIN_DIRECTORY/$NAME/$CHAPTER" || 
    mkdir -p "$MAIN_DIRECTORY/$NAME/$CHAPTER"
  cd "$MAIN_DIRECTORY/$NAME/$CHAPTER"

  BASE_URL="https://rawmanga.top/viewer/$NAME/$CHAPTER"

  echo -n "Number of pages: "
  NUMBER_OF_PAGES=$(countPages $BASE_URL)
  echo "$NUMBER_OF_PAGES"

  echo -n "Downloaded: "
  PAGE_NUMBER=$(lastPageDownloaded "$MAIN_DIRECTORY/$NAME/$CHAPTER")
  echo "$PAGE_NUMBER"

  #echo -n "($NUMBER_OF_PAGES pages, $PAGE_NUMBER downloaded)"
  while (( $PAGE_NUMBER <= $NUMBER_OF_PAGES ))
  do
    progressBar $PAGE_NUMBER $NUMBER_OF_PAGES
    wget -O "${NAME}_${CHAPTER}_$(threeDigits $PAGE_NUMBER).jpeg" --quiet --continue "$BASE_URL/$PAGE_NUMBER"

    PAGE_NUMBER=$((PAGE_NUMBER + 1))
  done
  echo -e "\nComplete!"
}

lastPageDownloaded(){
  # It's dull, but it works
  echo $1/* | tr ' ' '\n' | wc -w
}

threeDigits(){
  n=$1
  test $1 -lt 100 && n="0$1"
  test $1 -lt 10  && n="00$1"

  echo $n
}

cutField(){
  # $1 is the string
  # $2 is the field number 
  echo $1 | cut --delimiter '/' --fields $2
}

countPages(){
  # $1 = Base url
  number=1
  while [ $(curl -s "$1/$number" | grep -ic error) -eq 0 ]
  do
    number=$((number + 1))
  done
  echo $((number - 1))
}

progressBar() {
  # Process data
  let _progress=(${1}*100/${2}*100)/100
  let _done=(${_progress}*4)/10
  let _left=40-$_done
  # Build progressbar string lengths
  _fill=$(printf "%${_done}s")
  _empty=$(printf "%${_left}s")

  # Build progressbar strings and print the ProgressBar line
  # Output example:                           
  # Progress : [########################################] 100%
  printf "\rProgress : [${_fill// /#}${_empty// /-}] ${_progress}%%"
}

create_directories

TITLE=$(chooseManga)
test "$TITLE" || exit

CHAPTER=$(chooseChapter $TITLE)
test "$CHAPTER" || exit

downloadChapter "$CHAPTER"
